// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApyvwkHdFdJTarJ7InGh68rADd9ZRrK_g',
    appId: '1:260502621847:web:b915a6f915eeea2368e3d2',
    messagingSenderId: '260502621847',
    projectId: 'shambaeye-d01fc',
    authDomain: 'shambaeye-d01fc.firebaseapp.com',
    storageBucket: 'shambaeye-d01fc.firebasestorage.app',
    measurementId: 'G-LSN2BG5X9T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEYrhyI2eYSyBuxH8NGYmJFStJtHQzyGA',
    appId: '1:260502621847:android:337ee3a1c72d2a1c68e3d2',
    messagingSenderId: '260502621847',
    projectId: 'shambaeye-d01fc',
    storageBucket: 'shambaeye-d01fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwJUut8N77a_ZihfJkPeJAVzdIBEDCO70',
    appId: '1:260502621847:ios:b61115d77e236c0868e3d2',
    messagingSenderId: '260502621847',
    projectId: 'shambaeye-d01fc',
    storageBucket: 'shambaeye-d01fc.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwJUut8N77a_ZihfJkPeJAVzdIBEDCO70',
    appId: '1:260502621847:ios:b61115d77e236c0868e3d2',
    messagingSenderId: '260502621847',
    projectId: 'shambaeye-d01fc',
    storageBucket: 'shambaeye-d01fc.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApyvwkHdFdJTarJ7InGh68rADd9ZRrK_g',
    appId: '1:260502621847:web:864e5654740b1a3568e3d2',
    messagingSenderId: '260502621847',
    projectId: 'shambaeye-d01fc',
    authDomain: 'shambaeye-d01fc.firebaseapp.com',
    storageBucket: 'shambaeye-d01fc.firebasestorage.app',
    measurementId: 'G-Q3TDJKLXDL',
  );
}
